### ISSUE TITLE
does not seem to work with 1.0.12.9

### ISSUE THREAD

**Issue by alexwwyy** [iqqmuT/civ6-cheat#8]
It worked perfectly for me for the original release of Gathering Storm, version 1.0.0.290.  Now I've updated to the latest version 1.0.12.9, and it stopped working with this error.

pkg/prelude/bootstrap.js:1751
      return wrapper.apply(this.exports, args);
                     ^

Error: Error reading string: {"pos":115318,"next4":{"type":"Buffer","data":[78,68,89,0]}}
    at readUtfString (/snapshot/civ6-cheat/index.js)
    at parseEntry (/snapshot/civ6-cheat/index.js)
    at Object.parse (/snapshot/civ6-cheat/index.js)
    at Object.<anonymous> (/snapshot/civ6-cheat/index.js)
    at Module._compile (pkg/prelude/bootstrap.js:1751:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.runMain (pkg/prelude/bootstrap.js:1804:12)
    at internal/main/run_main_module.js:17:47

The save file is here.

https://drive.google.com/file/d/1zEoMx6l6ervgA6Yb5XD2XQsR49h8OgNc/view?usp=sharing

**Comment by alexwwyy** [comment]
Found that civ6-save-parser has a commit six months ago for better handling of arrays.  Merged that and it works fine now.

**Comment by iqqmuT** [comment]
Excellent, thanks for the work! Can you test civ6-cheat v1.3.0 and if it works, close this issue?

**Comment by alexwwyy** [comment]
Yes it does.
